contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dna channel"
    url: https://nfcore.slack.com/channels/dna
    about: Discussion about the nf-core/dna pipeline
